nadavzeldin/maple-rouge-like

src/main/java/client/command/CommandsExecutor.java, src/main/java/net/server/channel/handlers/ChangeMapHandler.java
=> when player die he goes to jail

src/main/java/net/server/channel/handlers/ChangeMapHandler.java
=> add jailtime

config.yaml, src/main/java/client/Character.java
=> easy_travel

scripts/npc/2007.js
=> Improve welcome message

scripts/npc/2007.js, src/main/java/client/Character.java, src/main/java/constants/game/GameConstants.java, src/main/java/server/life/MonsterInformationProvider.java
=> Loot lizard spawning

scripts/npc/2007.js, src/main/java/client/Character.java, src/main/java/net/server/channel/handlers/UseItemHandler.java, src/main/java/server/ItemInformationProvider.java, src/main/java/server/life/MonsterInformationProvider.java
=> birth day potion adds all ap +1

src/main/java/constants/game/GameConstants.java
=> reset ap command with @resetAp

src/main/java/constants/id/ItemId.java, src/main/java/server/life/MonsterInformationProvider.java
=> add merge coint to candle drop

scripts/npc/2007.js, src/main/java/client/Character.java, src/main/java/client/SkillFactory.java, src/main/java/client/command/CommandsExecutor.java, src/main/java/constants/game/GameConstants.java
=> Small improvements

config.yaml, scripts/map/onUserEnter/go10000.js, src/main/java/client/Character.java
+ better pq exp and return of pin for ch deletion
+ add 4th jobs
=> + ui message for all

src/main/java/client/Character.java
=> to protect characters

src/main/java/client/command/CommandsExecutor.java, src/main/java/client/command/commands/gm0/ShopCommand.java, src/main/java/server/life/MonsterInformationProvider.java
=> add shop command

src/main/java/client/Character.java
=> - 4th job from level 120 and not 90 :P

src/main/java/net/server/channel/handlers/ChangeMapHandler.java
=> - notfiy_player_death

scripts/npc/9030000.js, src/main/java/client/command/commands/gm6/MergeCommand.java
=> balance merge, using diminishing returns and item levelup

src/main/java/client/command/CommandsExecutor.java
=> - hotfix-merge-command, only admin

src/main/java/client/command/commands/gm0/SellCommand.java
=> - sell_command_avoid_cash_in_all

src/main/java/client/command/CommandsExecutor.java, src/main/java/client/command/commands/gm0/RollCommand.java, src/main/java/client/command/commands/gm0/SellCommand.java, src/main/java/constants/game/GameConstants.java
=> Sell <type> <slotAmount> and @roll command

scripts/npc/9030000.js, src/main/java/constants/id/ItemId.java
=> - change_merge_coin_to_stackables

src/main/java/client/Character.java
=> - increase_slot_by_alot

src/main/java/server/life/MonsterInformationProvider.java
=> increase_merge_coin_quantity_drop

src/main/java/net/server/channel/handlers/ChangeMapHandler.java
=> remove wheel reviver cashop item

src/main/java/client/Character.java
=> gain achivement one time ..

src/main/java/client/Achievement.java, src/main/java/client/AchievementConstants.java, src/main/java/client/Character.java, src/main/java/client/command/commands/gm1/BuffMeCommand.java, src/main/java/constants/game/GameConstants.java
1. remove cake, too op
2. buff me won't revive anymore
3. max level is 200, also for cygnus
4. add cyngus to 4th job now that remove level cap
5. every 20 levels + 20 to slots
6. level 20 achievement now character will be level 1 with a lot more stats (+40 for all)
7. hopefully fix avoiding getting same job twice
8. hopefully fix dup
=> bug fixes:

src/main/java/client/Character.java, src/main/java/constants/inventory/ItemConstants.java, src/main/java/net/server/channel/handlers/UseItemHandler.java
=> add a 2 secs cooldown to potion

src/main/java/constants/id/MapId.java
=> new jail room without portal to leave..

scripts/npc/gachapon.js, src/main/java/scripting/npc/NPCConversationManager.java
=> global gatcha

src/main/java/client/Character.java
=> remove 4th job

src/main/java/client/Character.java, src/main/java/net/server/channel/handlers/ChangeMapHandler.java
resetInventory wasn't working. Redid the function and unkillable works properly now
Suggest testing and deploying asap, there was a dupe with unkillable causing desync and this fixes it
=> fixed unkillable bug

src/main/java/client/Character.java
=> Fix botainables slots

src/main/java/client/command/CommandsExecutor.java, src/main/java/client/command/commands/gm0/BuyExpCommand.java, src/main/java/client/command/commands/gm1/BuyExpCommand.java
Buy 3x exp coupon with command @buyexp instead of going into the cash shop, check if available nx before buying and applying
=> Buy 3x exp coupon with command @buyexp

src/main/java/client/command/commands/gm1/BuffMeCommand.java
Same usage @Buffme but now include all the previous buffs from each job the character had.
=> Improved Buffme - Include all previous buffs from previous jobs

scripts/npc/2042000.js, scripts/npc/2042003.js, scripts/npc/2042004.js, scripts/npc/gachapon.js, src/main/java/scripting/AbstractPlayerInteraction.java
Resolves the following issues:
(1) Users are unable to speak with NPCs after ending chat from Gachapon multi-roll quantity select screen.  This is because the cm.sendGetNumber() method has a different return type for the mode.  Added handling to properly end chat and dispose NPC.
(2) If a user enters DOOM and then leaves the party, they are stuck in the map and able to keep talking to the NPC to receive pitches over and over.  This is because the cm.warpParty() method does nothing if the user is not in a party, and the NPC is unable to warp the user when not in a party.  Added handling to warp player out when not in a party and updated NPC text to indicate the user cannot continue if they are not in a party.
=> Gachapon & DOOM bug fixes

src/main/java/constants/game/GameConstants.java, src/main/java/constants/id/MapId.java, src/main/java/server/life/SpawnPoint.java, src/main/java/server/maps/MapFactory.java, src/main/java/server/maps/MapleMap.java
=> controlled_spawn_rates

src/main/java/server/life/HourlySpawnBoostManager.java
=> spawn_fixes

src/main/java/client/AscensionConstants.java, src/main/java/client/Character.java, src/main/java/client/command/commands/gm0/AscensionCommand.java, src/main/java/server/StatEffect.java, src/main/java/server/maps/MapleMap.java
- update world to 10 channels
- channel 10 is buffed with x5 hp and x5 exp
- ECHO_OF_HERO now scales with ascensions +2% for weapon attack and magic attack for each ascension
- New ascension Infinite, which can be stackable, each stack give +2 AP each level up. For example, if ascended Infinite(10) you will get each level up base 5 + 20
=> fun updates

src/main/java/server/StatEffect.java
=> - Transformation are blocked due to exploits

src/main/java/client/Character.java, src/main/java/client/command/CommandsExecutor.java
=> - while dead can't use commands

src/main/java/constants/id/MapId.java, src/main/java/server/maps/MapFactory.java
-- 270030400 - Time Lane - Road to Oblivion4
-- 800020130 - Zipangu - Encounter with the Buddha
-- 220060400 - Ludibrium - Warped Passage (this map could use a huge boost, I believe the flat spawn rate is very little)
-- 220070400 - Ludibrium - Forgotten Passage
=> - enhance end game maps x2 spawn rates:

src/main/java/server/maps/MapleMap.java
=> x5 hp limit to 2bil

src/main/java/server/StatEffect.java
=> Avoid rebuff buffme

src/main/java/server/StatEffect.java
=> revert echo buffs

scripts/npc/gachapon.js, src/main/java/constants/game/GameConstants.java, src/main/java/constants/id/MapId.java, src/main/java/scripting/npc/NPCConversationManager.java
purged most of the gachapon, will adjust more another time. reduced 10m -> 5m so it can be used more and tested easily. (getting 1b mesos for 100 rolls is a pain) can worry about mesos sink later when the pool gets balanced
added .@goto scarga (boss entrance)
added .@goto yakuza (boss entrance)
changed pap location to be more "normal"
=> small cmd and gachapon revamp

config.yaml, scripts/npc/oreStorage.js, scripts/npc/scrollStorage.js, scripts/npc/setKeybind.js, src/main/java/client/Character.java, src/main/java/client/command/commands/gm0/ShowRatesCommand.java, src/main/java/constants/game/GameConstants.java, src/main/java/constants/id/ItemId.java, src/main/java/net/server/channel/handlers/UseItemHandler.java, src/main/java/server/ResourceStorage.java
Big batch of changes from my suggestions thread :-)
**Server**
- Updates map dropped item limit to 500 (previously 200)
- Makes TP rock locations account-wide rather than character-specific
- **NOTE** - this will require either a SQL migration or a wipe; I would just wait for the wipe to merge these changes if it's coming soon, otherwise you can see the [SQL script in the commit message for this change](https://github.com/cpurules/maple-rouge-like/commit/9c5f892bea9dde5b015ccd7f34a5a96890b15aa3)
- Update resource storage to also store `Happy birthday` (all-stat cakes) in scroll storage
- Update scroll/ore resource storage to have filter option
- Update `@showrates` command to include line-item for hoarder x5 if applicable
**Client**
NOTE: This involves a new `dinput8.dll` needing to be …
=> QOL Updates

database/sql/1-db_database.sql, src/main/java/client/Character.java, src/main/java/net/server/channel/handlers/TakeDamageHandler.java, src/main/java/net/server/channel/handlers/UseSummonBagHandler.java, src/main/java/scripting/npc/NPCConversationManager.java, src/main/java/server/StatEffect.java, src/main/java/server/maps/MapleMap.java
- cant summon in towns.
- remove bugged gacha item
- buffed channel bosses won't get extra HP and EXP
- buffed channel monsters (bosses and mobs) do x3 damage
- removing bugged transformation gacha USE_ITEMS
- blocking NightWalker.SHADOW_PARTNER to avoid crashes
- avoid candle spawning in towns and starting map
=> Bug fixes 2

src/main/java/client/command/commands/gm6/MergeCommand.java
=> new merge system

scripts/npc/gachapon.js, src/main/java/scripting/npc/NPCConversationManager.java
Tested!
Added new scroll option, bunch of 10% scrolls.
Gachapon now cost 50m a roll.
Lots of items added to the pool to decrease odds getting one specific item.
=> Gachapon fix

src/main/java/client/Character.java
=> Bug fix 30 3

src/main/java/client/command/commands/gm2/ReachCommand.java
=> - reach to only work for party members

src/main/java/scripting/npc/NPCConversationManager.java
=> - Elemental Staff 8

scripts/npc/9900000.js, src/main/java/client/AscensionConstants.java, src/main/java/client/Character.java, src/main/java/client/Client.java, src/main/java/client/command/CommandsExecutor.java, src/main/java/client/command/commands/gm0/AscensionCommand.java, src/main/java/client/command/commands/gm0/StorageCommand.java, src/main/java/client/command/commands/gm0/StylistCommand.java, src/main/java/client/command/commands/gm2/ReachCommand.java, src/main/java/client/processor/npc/StorageProcessor.java, src/main/java/constants/game/GameConstants.java, src/main/java/net/server/channel/handlers/PlayerLoggedinHandler.java
- new @storage command
- new ascension Stylist | @style -> teleport to unique map with extra cosmetic options (each cost 100k) asked by @cpu
- new ascension Risktaker | unlock buffed channel (3)
- new ascension Heirloom | enable use @storage from jail once per character
=> new ascension

scripts/npc/2003.js
=> improve text

src/main/java/client/Client.java, src/main/java/net/server/channel/handlers/PlayerLoggedinHandler.java
Fixes issues where players can still get into (and get stuck in) channel 3
https://github.com/user-attachments/assets/67aa0a2a-8a2d-4bea-a62f-50ea0db6983d
=> Fixes for blocked buff channel

database/sql/1-db_database.sql, scripts/npc/resourceStorage.js, scripts/npc/rewardsStorage.js, src/main/java/client/Character.java, src/main/java/client/CharacterSettings.java, src/main/java/client/command/CommandsExecutor.java, src/main/java/client/command/commands/gm0/RewardsCommand.java, src/main/java/constants/id/NpcId.java
=> rewards system reworked

src/main/java/client/AccountExtraDetails.java, src/main/java/client/Character.java, src/main/java/client/command/commands/gm0/ShowRatesCommand.java, src/main/java/client/command/commands/gm6/MergeCommand.java, src/main/java/net/server/channel/handlers/TakeDamageHandler.java
=> Features bulk
